colors1 = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgrey",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "grey",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgrey",
    "lightgreen",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
]
colors = [
    'rgba(38, 24, 74, 0.8)',
    'rgba(71, 58, 131, 0.8)',
    'rgba(122, 120, 168, 0.8)',
    'rgba(164, 163, 204, 0.85)',
    'rgba(190, 192, 213, 1)',
]

colors_pie_graph = [
    'rgba(255, 255, 255, 0.8)',   # 1 - Branco
    'rgba(255, 245, 225, 0.8)',   # 2 - Quase branco com toque laranja
    'rgba(255, 230, 190, 0.8)',   # 3 - Laranja bem claro
    'rgba(255, 215, 150, 0.8)',   # 4 - Laranja claro
    'rgba(255, 195, 110, 0.85)',  # 5 - Laranja médio-claro
    'rgba(255, 175, 70, 0.85)',   # 6 - Laranja médio
    'rgba(255, 160, 30, 0.9)',    # 7 - Laranja forte
    'rgba(255, 140, 0, 1)',       # 8 - Laranja intenso/final
]

time_interval = {
    'D*': 0,
    'D1': 1,
    'D7': 7,
    'D30': 30,
}

status_options = {
    "F. GERAL": "OP",
    "CANCELADO": "CL",
    "DIGITAÇÃO": "TY",
    "F. MEDICA": "RW",
    "CONCLUIDO": "CD",
    "F. DIGITADOR":"TO",
}